name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-readme:
    permissions: write-all
    runs-on: ubuntu-latest
    env:  
      TEST_VARIABLE_1: ${{ vars.TEST_VARIABLE_1 }} 
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.16

      - name: Use variables
        run: |
          echo "checking variable : $TEST_VARIABLE_1"
        
      - name: Run Go code
        run: go run main.go
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin master
          git add .
          git commit -m "Update README with latest weather data"
          git push -u origin master 
    
